<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Healthy Eating</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    </head>
    <body>
        <div class="toBuy">
            <h1>Things to Buy:</h1>

            <?php
            echo HealthyEating\helpers\DisplayShoppingItemsHelper::displayShoppingItems($shoppingItems);
            ?>
        </div>

        <div class="add" id="add">
            <h1>Add Item to List:</h1>

            <?php
            echo HealthyEating\helpers\AddShoppingItemHelper::addShoppingItemsForm();
            ?>
        </div>
    </body>
</html>
